name: FishingPlugin
version: '1.5-SNAPSHOT'
main: org.hark7.fishingPlugin.FishingPlugin
api-version: '1.21'

permissions:
  fishingplugin.command.fish:
    description: FishingPluginのコマンド使用権限
    default: true
  fishingplugin.op:
    description: OP専用のコマンド使用権限
    default: op