name: FishingPlugin
version: '1.5-SNAPSHOT'
main: org.hark7.fishingPlugin.FishingPlugin
api-version: '1.21'

commands:
  fishtop:
    description: 釣りランキングを表示します
    usage: /<command> <ランキングの種類>
  upgradepole:
    description: 釣り竿をアップグレードします
    usage: /<command>
  resetlevel:
    description: プレイヤーの釣りレベルをリセットします（OP専用）
    usage: /<command> <プレイヤー名>
    permission: fishingplugin.op
    permission-message: このコマンドを使用する権限がありません。
permissions:
  fishingplugin.op:
    description: FishingPluginのOP権限
    default: op