# Locale settings for the application
Language:
  Default: ja_JP
  Supported:
    - ja_JP

# Database connection settings
# Don't modify values in DatabaseVersion section
DatabaseVersion:
  PlayersTableVersion: 1
  CountsTableVersion: 1