# Locale settings for the application
Language:
  Default: "ja-JP"
  Supported:
    - "ja-JP"

# Database connection settings
# Don't modify values in DatabaseVersion section
DatabaseVersion:
  PlayersTableVersion: 1
  CountsTableVersion: 1